package ru.diploma.tarotapplication.ui.components

import ru.diploma.tarotapplication.R

val iconsMap = mapOf(
    "default" to R.drawable.categ_default,
    "relations" to R.drawable.categ_relations,
    "work" to R.drawable.categ_work,
    "health" to R.drawable.categ_health,
    "person" to R.drawable.categ_person,
    "result" to R.drawable.categ_result,
    "finish" to R.drawable.categ_finish,
    "advice" to R.drawable.categ_advice,
    "warn" to R.drawable.categ_warn,
    "money" to R.drawable.categ_money,
    "keywords" to R.drawable.categ_keywords,
    "situation" to R.drawable.categ_situation,
    "location" to R.drawable.categ_location,
    "major_arcana" to R.drawable.major_arcana,
    "zodiac_aquarius" to R.drawable.zodiac_aquarius,
    "zodiac_aries" to R.drawable.zodiac_aries,
    "zodiac_taurus" to R.drawable.zodiac_taurus,
    "zodiac_cancer" to R.drawable.zodiac_cancer,
    "zodiac_leo" to R.drawable.zodiac_leo,
    "zodiac_virgo" to R.drawable.zodiac_virgo,
    "zodiac_libra" to R.drawable.zodiac_libra,
    "zodiac_scorpio" to R.drawable.zodiac_scorpio,
    "zodiac_sagittarius" to R.drawable.zodiac_sagittarius,
    "zodiac_gemini" to R.drawable.zodiac_gemini,
    "zodiac_pisces" to R.drawable.zodiac_pisces,
    "zodiac_capricorn" to R.drawable.zodiac_capricorn,
    "element_wind" to R.drawable.element_wind,
    "element_fire" to R.drawable.element_fire,
    "element_water" to R.drawable.element_water,
    "element_earth" to R.drawable.element_earth,
    "element_fire_water" to R.drawable.element_fire_water,
    "element_jupiter" to R.drawable.element_jupiter,
    "element_mars" to R.drawable.element_mars,
    "element_mercury" to R.drawable.element_mercury,
    "element_moon" to R.drawable.element_moon,
    "element_neptun" to R.drawable.element_neptun,
    "element_pluto" to R.drawable.element_pluto,
    "element_saturn" to R.drawable.element_saturn,
    "element_sun" to R.drawable.element_sun,
    "element_uranium" to R.drawable.element_uranium,
    "element_venus" to R.drawable.element_venus,
    "major" to R.drawable.major_arcana,
    "cups" to R.drawable.cups,
    "swords" to R.drawable.swords,
    "wands" to R.drawable.wands,
    "coins" to R.drawable.coins,
    "astrology" to R.drawable.astrology,
)